apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Module
      name: vastnfs
    patch: |-
      - op: add
        path: /spec/imageRepoSecret
        value:
          name: ${KMM_PULL_SECRET}
